/**
 * init.ts - Enhanced Application Initialization
 * V2 TypeScript - Proper V1 compatibility with view registry support
 * 
 * Initialize OneJS application with config from window.APP_CONFIGS
 * Handles:
 * 1. View registry loading (V2)
 * 2. Service initialization (Http, Store, Event)
 * 3. Router setup with routes
 * 4. View manager initialization
 * 5. App ready event dispatch
 */

import { Application } from "../app/Application.js";

/**
 * Initialize application from global config
 * Proper flow: Container → Views → Services → Router → Navigation
 */
export async function initApp(appInstance?: Application): Promise<void> {
    const app = appInstance || (typeof (window as any).App !== 'undefined' ? (window as any).App : null);
    
    if (!app) {
        console.error('❌ No Application instance provided!');
        return;
    }

    const config = (window as any).APP_CONFIGS;
    if (!config) {
        console.error('❌ APP_CONFIGS not found! Please define window.APP_CONFIGS.');
        return;
    }

    console.log('🚀 OneJS V2 Application Initialization');
    console.log('════════════════════════════════════════\n');

    try {
        // PHASE 1: Load view registry (V2 specific)
        await initializeViewRegistry(app);

        // PHASE 2: Initialize application core
        initializeApplication(app, config);

        // PHASE 3: Initialize services
        initializeServices(app, config);

        // PHASE 4: Setup router
        initializeRouter(app, config);

        // PHASE 5: Setup navigation
        initializeNavigation(app);

        // PHASE 6: Dispatch ready event
        dispatchAppReady(app, config);

        // PHASE 7: Setup view activation
        updateActiveNav(window.location.pathname);

        console.log('✅ OneJS Application Initialized Successfully!');
        console.log('════════════════════════════════════════\n');

    } catch (error) {
        console.error('❌ Application initialization failed:', error);
        throw error;
    }
}

/**
 * PHASE 1: Initialize View Registry (V2)
 * Attempt to load pre-compiled view registry if available
 */
async function initializeViewRegistry(app: Application): Promise<void> {
    console.log('📁 Phase 1: Loading View Registry...');
    
    try {
        // Check if registry exists (generated by build system)
        const registryPath = './dist/v2/views-registry.js';
        try {
            const registryModule = await import(registryPath);
            const registry = registryModule.default || registryModule.ViewRegistry;
            
            if (registry && typeof registry === 'object') {
                app.View.setViewRegistry(registry);
                console.log(`   ✓ View registry loaded: ${Object.keys(registry).length} views`);
                return;
            }
        } catch (registryError) {
            // Registry not available, fall back to runtime compilation
            console.log('   ⚠️  Pre-compiled registry not found, will use runtime compilation');
        }
        
    } catch (error) {
        console.log('   ⚠️  Registry initialization error:', (error as Error).message);
    }
    
    console.log('   ✓ View registry phase completed\n');
}

/**
 * PHASE 2: Initialize Application Core
 */
function initializeApplication(_app: Application, config: any): void {
    console.log('🏗️  Phase 2: Application Core...');
    
    // Set container if specified
    if (config.container) {
        console.log(`   ✓ Container: ${config.container}`);
    }
    
    // Initialize core components
    if (config.debug) {
        console.log('   ✓ Debug mode enabled');
    }
    
    console.log('   ✓ Application core initialized\n');
}

/**
 * PHASE 3: Initialize Services
 */
function initializeServices(app: Application, config: any): void {
    console.log('⚙️  Phase 3: Services...');
    
    // Http Service
    if (app.Http && config.services?.http) {
        console.log('   ✓ Http service configured');
    }
    
    // Store Service
    if (app.Store) {
        console.log('   ✓ Store service initialized');
    }
    
    // Event Service
    if (app.Event) {
        console.log('   ✓ Event service initialized');
    }
    
    console.log('   ✓ Services initialized\n');
}

/**
 * PHASE 4: Initialize Router
 */
function initializeRouter(app: Application, config: any): void {
    console.log('🗺️  Phase 4: Router...');
    
    if (!app.Router) {
        console.log('   ⚠️  Router not available');
        return;
    }
    
    // Setup routes if provided
    if (config.routes && Array.isArray(config.routes)) {
        console.log(`   ✓ Routes configured: ${config.routes.length} routes`);
    }
    
    console.log('   ✓ Router initialized\n');
}

/**
 * PHASE 5: Initialize Navigation
 */
function initializeNavigation(app: Application): void {
    console.log('🧭 Phase 5: Navigation...');
    
    try {
        if (app.Router) {
            // Setup route change handler
            console.log('   ✓ Route change handler set up');
        }
        
        console.log('   ✓ Navigation initialized\n');
        
    } catch (error) {
        console.log('   ⚠️  Navigation setup error:', (error as Error).message, '\n');
    }
}

/**
 * PHASE 6: Dispatch App Ready Event
 */
function dispatchAppReady(app: Application, config: any): void {
    console.log('📡 Phase 6: App Ready...');
    
    // Custom ready callback
    if (config.onReady && typeof config.onReady === 'function') {
        try {
            config.onReady(app);
            console.log('   ✓ Custom ready callback executed');
        } catch (error) {
            console.log('   ⚠️  Ready callback error:', (error as Error).message);
        }
    }
    
    // Dispatch global ready event
    if (typeof window !== 'undefined') {
        window.dispatchEvent(new CustomEvent('onejs:ready', { detail: { app } }));
        console.log('   ✓ App ready event dispatched');
    }
    
    console.log('   ✓ App ready phase completed\n');
}

/**
 * PHASE 7: Update Active Navigation
 */
export function updateActiveNav(currentPath?: string): void {
    console.log('🎯 Phase 7: Active Navigation...');
    
    const path = currentPath || window.location.pathname;
    
    // Update active nav classes
    document.querySelectorAll('[one-link]').forEach((link: Element) => {
        const href = link.getAttribute('one-link');
        const element = link as HTMLElement;
        
        if (href === path) {
            element.classList.add('active');
        } else {
            element.classList.remove('active');
        }
    });
    
    console.log(`   ✓ Navigation updated for: ${path}\n`);
}

export default initApp;